collections/Arch_Selden/MS_Arch_Selden_A_1.xml
Also removed link to external site that no longer works.
=> Add Digital Bodleian Link for MS Arch. Seld. A. 1

collections/Junius/MS_Junius_11.xml
=> Tidy up Junius 11 XML

collections/Holkham_misc/MS_Holkham_misc_48.xml
=> Update Holkham Misc 48 link to digital bodleian

collections/Merton/Merton_College_MS_87.xml, collections/Merton/Merton_College_MS_88.xml, collections/Merton/Merton_College_MS_89.xml, collections/Merton/Merton_College_MS_90.xml
=> add merton ms 88

collections/Hamilton/MS_Hamilton_1.xml, collections/Laud_Misc/MS_Laud_Misc_96.xml
Per Henrike's request, "Lord's Prayer" changed to "Intercessory prayer". Henrike requested "Middle Low German intercessory prayer", but I don't know that we need the language repeated in the title.
=> change msItem title in MS. Don. e. 248

collections/Don/MS_Don_e_248.xml
per Henrike's request, changed Psalterii sancti iohannis to Psalterium de sancto Johanne
=> MS. Don. e. 248 -- changed msItem name

collections/Laud_Misc/MS_Laud_Misc_101.xml, collections/Laud_Misc/MS_Laud_Misc_106.xml, collections/Laud_Misc/MS_Laud_Misc_122.xml, collections/Laud_Misc/MS_Laud_Misc_124.xml, collections/Laud_lat/MS_Laud_Lat_117.xml
Laud Lat. 117, Laud Misc. 101, 106, 122 and 124
=> updates to 5 files /PolonskyGerman

collections/Christ_Church/Christ_Church_MS_114.xml, collections/Hamilton/MS_Hamilton_2.xml, collections/Hamilton/MS_Hamilton_6.xml, collections/Laud_Misc/MS_Laud_Misc_88.xml, collections/Laud_Misc/MS_Laud_Misc_89.xml, collections/Laud_lat/MS_Laud_Lat_103.xml, collections/Laud_lat/MS_Laud_Lat_108.xml, collections/Laud_lat/MS_Laud_Lat_115.xml, collections/Tanner/MS_Tanner_170.xml
Adds facsimile links for manuscripts added to Digital Bodleian in June and July 2019.
=> Digitized items july 2019

collections/Canon_Misc/MS_Canon_Misc_562.xml
The link to the SC page was incorrect for Canon Misc 562.
=> Fix SC link for Canon Misc 562

collections/Laud_Misc/MS_Laud_Misc_274.xml, collections/Laud_Misc/MS_Laud_Misc_281.xml, collections/Laud_Misc/MS_Laud_Misc_510.xml, collections/Laud_Misc/MS_Laud_Misc_538.xml
Adds Digital Bodleian and project site links for Polonsky MSS completed in December 19 and Jan 20.
=> Polonsky links 2020 02 07

collections/Canon_Misc/MS_Canon_Misc_352.xml, collections/Holkham_gr/MS_Holkham_Gr_76.xml
including a correction to MS. Canon. Misc. 352
=> MS. Holkham Gr. 76: new desc, authority updates, etc.

collections/Add_E/MS_Add_E_3_R.xml
Adds a link to Digital Bodleian for MS. Add. E. 3 (R)
=> Add link to Digital Bodleian for MS. Add. E. 3 (R)

collections/Bodl/MS_Bodl_277.xml
=> Add missing link to MS Bodl 277

collections/Exeter_College/Exeter_College_MS_158.xml, collections/Exeter_College/Exeter_College_MS_186.xml, collections/Exeter_College/Exeter_College_MS_21.xml, collections/Exeter_College/Exeter_College_MS_23.xml, collections/Exeter_College/Exeter_College_MS_25.xml, collections/Exeter_College/Exeter_College_MS_4.xml, collections/Exeter_College/Exeter_College_MS_46.xml, collections/Exeter_College/Exeter_College_MS_47.xml
I reused an old script to add these links. All validate.
=> Add surrogates links in eight Exeter manuscripts to Digital Bodleian

collections/Douce/MS_Douce_80.xml
Deco description added for MS. Douce 80
=> MS. Douce 80 deco desc

St_John's_College_MS_34.xml, collections/St_Johns_College/ St_Johns_College_MS_34.xml
Made changes to encoding as discussed; added <bibl> elements throughout where it seemed appropriate, unsure if these should be kept in.
=> Add St_John's_College_MS_34

collections/St_Johns_College/St_Johns_College_MS_144.xml, collections/St_Johns_College/St_Johns_College_MS_59.xml
Do the column dimensions (particularly the extra details about some quires) need more marking up?
Would 'paraph' be an appropriate value for the final decoNote type attribute? 
I couldn't find a record for John Stonor (donor in the second provenance) - should I attempt to create an authority record for him?
Thank you!
=> Add St_Johns_College_MS_59

collections/St_Johns_College/St_Johns_College_MS_117.xml, collections/St_Johns_College/St_Johns_College_MS_121.xml, collections/St_Johns_College/St_Johns_College_MS_18.xml, collections/St_Johns_College/St_Johns_College_MS_19.xml, collections/St_Johns_College/St_Johns_College_MS_205.xml, collections/St_Johns_College/St_Johns_College_MS_28.xml, collections/St_Johns_College/St_Johns_College_MS_87.xml
Unsure if I marked up the added items in ms 28 correctly, particularly added item c.
=> St John's MSS 18, 28, 87, 205

collections/Douce/MS_Douce_390.xml
New description; I have sent you information for 'Maestro della Parousia' authority record based on *Dizionario biografico dei miniatori italiani*, <http://hdl.handle.net/11562/318020>.
=> MS. Douce 390: new description

collections/Lat_liturg/MS_Lat_liturg_d_38.xml
This is a combination of the descriptions by Kidd and Solopova with my own additions.
=> MS. Lat. liturg. d. 38: Revise description

collections/Lat_th/MS_Lat_th_e_22.xml
Most of these sermons can be found in other manuscripts, and some have attributions floating around, but none of them looked plausible enough to me to include.
=> MS. Lat. th. e. 22: Revise description

collections/Lat_th/MS_Lat_th_d_18.xml
@adunning - Peter ended up looking at this (partly by a mix up) but suggested some revisions which seem worth incorporating; in particular it seems useful to push the date back to 14th century (?) for at least some of the manuscript (the Greek cross watermark seems pretty clear evidence for that) (https://www.wasserzeichen-online.de/wzis/struktur.php?klassi=007001001003001&anzeigeIDMotif=7601) . I additionally noticed that the current collation statement isn't compatible with the division of the manuscript into 3 codicological units, so that may need reconsidering...
=> MS. Lat. th. d. 18 - Peter Kidd revisions

collections/Germ/MS_Germ_e_23.xml
All `<persName>`s (excepting Anselm) need a record; I have used VIAF IDs.
=> MS. Germ. e. 23: Mossman description

collections/St_Johns_College/St_Johns_College_MS_138.xml, collections/St_Johns_College/St_Johns_College_MS_62.xml, collections/St_Johns_College/St_Johns_College_MS_7.xml, collections/St_Johns_College/St_Johns_College_MS_79.xml
=> Updated encoding

collections/DOrville/MS_DOrville_153.xml
some checking still to be done in situ
=> MS. D'Orville 153: Peter Kidd description

collections/Lat_misc/MS_Lat_misc_e_2.xml
Awaiting comment from Nigel Palmer on language of the German text and localization of the main scribe
=> MS. Lat. misc. e. 2: Peter Kidd description

collections/Canon_Pat_Lat/MS_Canon_Pat_Lat_188.xml
=> MS. Canon. Pat. Lat. 188: Kidd description

collections/Add_A/MS_Add_A_188.xml
needs dimensions and ideally collation verifying. What do you think about presenting bibliography/links in this way?
=> MS. Add. A. 188: Peter Kidd description

collections/Douce/MS_Douce_367.xml
dimensions to be verified (ideally)
=> MS. Douce 367 - Peter Kidd description

collections/Canon_Pat_Lat/MS_Canon_Pat_Lat_52.xml
=> MS. Canon. Pat. Lat. 52: Kidd description

collections/St_Johns_College/St_Johns_College_MS_100.xml, collections/St_Johns_College/St_Johns_College_MS_140.xml, collections/St_Johns_College/St_Johns_College_MS_53.xml, collections/St_Johns_College/St_Johns_College_MS_73.xml
=> New entries (SJC Batch 3)

collections/French/MS_Fr_c_3.xml
Julia Mattison contributed this description, which I have converted from Word.
=> MS. Fr. c. 3: Mattison description

collections/St_Johns_College/St_Johns_College_MS_104.xml, collections/St_Johns_College/St_Johns_College_MS_12.xml, collections/St_Johns_College/St_Johns_College_MS_187.xml, collections/St_Johns_College/St_Johns_College_MS_20.xml, collections/St_Johns_College/St_Johns_College_MS_21.xml
New entries (SJC Batch 4 - MSS 12 and 187)
=> New Entries (SJC Batch 4 - MSS 12 and 187)

collections/St_Johns_College/St_Johns_College_MS_129.xml, collections/St_Johns_College/St_Johns_College_MS_84.xml
=> SJC Batch 6 (MSS 84 & 129)

collections/St_Johns_College/St_Johns_College_MS_189.xml, collections/St_Johns_College/St_Johns_College_MS_193.xml, collections/St_Johns_College/St_Johns_College_MS_194.xml, collections/St_Johns_College/St_Johns_College_MS_46.xml, collections/St_Johns_College/St_Johns_College_MS_88.xml
New entries. Batch 7 (SJC MSS 46, 88, 189, 193 & 194)
=> Batch 7 (SJC MSS 46, 88, 189, 193 & 194)

collections/St_Johns_College/St_Johns_College_MS_157.xml, collections/St_Johns_College/St_Johns_College_MS_207.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_1.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_3.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_2_5_and_17.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_4_and_24B.xml, collections/St_Johns_College/St_Johns_College_MS_24.xml, collections/St_Johns_College/St_Johns_College_MS_255.xml, collections/St_Johns_College/St_Johns_College_MS_26.xml, collections/St_Johns_College/St_Johns_College_MS_5.xml
New entries - MSS 5, 24, 26, 235 (fragment 1) and 235 (fragments 2, 5 & 17).
=> SJC Batch 8

collections/Rawl_B/MS_Rawl_B_214.xml
=> MS. Rawl. B. 214: New description

collections/St_Johns_College/St_Johns_College_MS_16.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_15.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_16.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_18.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_14_41_and_42.xml, collections/St_Johns_College/St_Johns_College_MS_27.xml, collections/St_Johns_College/St_Johns_College_MS_31.xml, collections/St_Johns_College/St_Johns_College_MS_64.xml, collections/St_Johns_College/St_Johns_College_MS_8.xml, collections/St_Johns_College/St_Johns_College_MS_9.xml
New entries (MS 16, MS 27, MS 64, MS 235 fragments 14, 41, and 42, MS 235 fragment 15)
=> SJC Batch 13

collections/St_Johns_College/St_Johns_College_MS_120.xml, collections/St_Johns_College/St_Johns_College_MS_125.xml, collections/St_Johns_College/St_Johns_College_MS_141.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_20.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_22.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_23.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_25_and_26.xml, collections/St_Johns_College/St_Johns_College_MS_65.xml, collections/St_Johns_College/St_Johns_College_MS_69.xml, collections/St_Johns_College/St_Johns_College_MS_74.xml
New entries - MS 65, MS 69, MS 141, MS 235 fragment 20, and MS 235 fragment 22
=> SJC Batch 15

places.xml
add variants and links from VIAF for recent additions of orgs to places.xml
=> Viaf update 22 1 6

collections/St_Johns_College/St_Johns_College_MS_106.xml, collections/St_Johns_College/St_Johns_College_MS_135.xml, collections/St_Johns_College/St_Johns_College_MS_171.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_29.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_30.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_31.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_28_and_36.xml, collections/St_Johns_College/St_Johns_College_MS_39.xml, collections/St_Johns_College/St_Johns_College_MS_57.xml, collections/St_Johns_College/St_Johns_College_MS_71.xml
New entries for MS 71, MS 106, MS 135, MS 235 fragments 28 and 36, and MS 235 fragment 29.
=> SJC Batch 17

collections/Bodl/MS_Bodl_779.xml
Started with rearranging data from DIMEV; will complete with consultation of original.
=> MS. Bodl. 779: New description

collections/St_Johns_College/St_Johns_College_MS_14.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_43.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_44.xml, collections/St_Johns_College/St_Johns_College_MS_256.xml, collections/St_Johns_College/St_Johns_College_MS_61.xml
New entries - MS 14, MS 61, MS 256, MS 235 fragment 43, MS 235 fragment 44
=> SJC Batch 22

collections/Laud_Misc/MS_Laud_Misc_570.xml
This is a basic description to enable the new images to go up for a reader – good enough to start?
=> MS. Laud Misc. 570: new description

collections/Auct_V/MSS_Auct_V_1_52a-b.xml, processing/customizations.xsl, processing/manuscripts.xquery
Indexing script changes and one record.
=> Former shelfmarks

collections/St_Johns_College/St_Johns_College_MS_132.xml, collections/St_Johns_College/St_Johns_College_MS_204.xml, collections/St_Johns_College/St_Johns_College_MS_235_Fragment_45.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_47.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_48.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_49.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_46_and_56.xml, collections/St_Johns_College/St_Johns_College_MS_42.xml, collections/St_Johns_College/St_Johns_College_MS_58.xml, collections/St_Johns_College/St_Johns_College_MS_63.xml
SJC Batch 23 - MS 58, MS 132, MS 204, MS 235 fragment 45, MS 235 fragments 46 and 56.
=> SJC Batch 23

collections/Hatton/MS_Hatton_116.xml
port of existing description from English MSS 1060-1220; hopefully won't need much checking
=> MS. Hatton 116, desc. from Em1060-1220 (studio migration)

collections/St_Johns_College/St_Johns_College_MS_108.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_52.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_55.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_51_and_53.xml, collections/St_Johns_College/St_Johns_College_MS_92.xml
New entries - MS 92, MS 108, MS 235 fragments 51 and 53, MS 235 fragment 52, and MS 235 fragment 55
=> SJC Batch 25

collections/St_Johns_College/St_Johns_College_MS_198.xml, collections/St_Johns_College/St_Johns_College_MS_2.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_61.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_63.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_57_and_59.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_58_and_60.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_62_and_68.xml, collections/St_Johns_College/St_Johns_College_MS_35.xml, collections/St_Johns_College/St_Johns_College_MS_49.xml, collections/St_Johns_College/St_Johns_College_MS_85.xml
New entries - MS 2, MS 35, MS 235 fragments 57 and 59, MS 235 fragments 58 and 60, and MS 235 fragment 61.
=> SJC Batch 26

collections/St_Johns_College/St_Johns_College_MS_235_fragment_66.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_67.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_69.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_70.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_71.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_72.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_94.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_95.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_96.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_97.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_98.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_100_and_101.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_99_and_102.xml
MS 235 fragments 66, 67, 69, 70, and 71
=> SJC Batch 29

collections/St_Johns_College/St_Johns_College_MS_235_fragment_105.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_106.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_109.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_110.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_111.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_103_and_104.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragments_107_and_108.xml
SJC MS 235 fragments 103/104, 105, 106, 107/108, 109, 110, and 111.
=> SJC Batch 31 - New entries

collections/Trinity_College/Trinity_College_MS_14.xml, collections/Trinity_College/Trinity_College_MS_15.xml, collections/Trinity_College/Trinity_College_MS_16A.xml, collections/Trinity_College/Trinity_College_MS_16B.xml, collections/Trinity_College/Trinity_College_MS_18.xml, collections/Trinity_College/Trinity_College_MS_19.xml, collections/Trinity_College/Trinity_College_MS_20.xml, collections/Trinity_College/Trinity_College_MS_21.xml, collections/Trinity_College/Trinity_College_MS_22.xml, collections/Trinity_College/Trinity_College_MS_23.xml, collections/Trinity_College/Trinity_College_MS_24.xml, collections/Trinity_College/Trinity_College_MS_25.xml, collections/Trinity_College/Trinity_College_MS_26.xml, collections/Trinity_College/Trinity_College_MS_27.xml, collections/Trinity_College/Trinity_College_MS_28.xml, collections/Trinity_College/Trinity_College_MS_29.xml, collections/Trinity_College/Trinity_College_MS_30.xml, collections/Trinity_College/Trinity_College_MS_38.xml, collections/Trinity_College/Trinity_College_MS_39.xml, collections/Trinity_College/Trinity_College_MS_40.xml, collections/Trinity_College/Trinity_College_MS_43.xml, collections/Trinity_College/Trinity_College_MS_44.xml, collections/Trinity_College/Trinity_College_MS_49.xml, collections/Trinity_College/Trinity_College_MS_53.xml, collections/Trinity_College/Trinity_College_MS_54.xml, collections/Trinity_College/Trinity_College_MS_55.xml, collections/Trinity_College/Trinity_College_MS_56.xml, collections/Trinity_College/Trinity_College_MS_57.xml, collections/Trinity_College/Trinity_College_MS_58.xml, collections/Trinity_College/Trinity_College_MS_59.xml
MS 28 Bede work amended but unsure of Augustine author and title key
=> 18 records 27/7

collections/Trinity_College/Trinity_College_MS_64.xml, collections/Trinity_College/Trinity_College_MS_65.xml, collections/Trinity_College/Trinity_College_MS_67.xml, collections/Trinity_College/Trinity_College_MS_68.xml, collections/Trinity_College/Trinity_College_MS_69.xml, collections/Trinity_College/Trinity_College_MS_70.xml
Some missing attributes - emailed Matthew.
=> Trinity MSS 64-70 updates

collections/St_Johns_College/St_Johns_College_MS_206.xml, collections/St_Johns_College/St_Johns_College_MS_43.xml, collections/St_Johns_College/St_Johns_College_MS_78.xml
New entries - MSS 43, 78, and 206
=> SJC Batch 33

collections/St_Johns_College/St_Johns_College_MS_113.xml, collections/St_Johns_College/St_Johns_College_MS_165.xml, collections/St_Johns_College/St_Johns_College_MS_183.xml
New entries - MS 113, MS 165, MS 183
=> SJC Batch 34

collections/St_Johns_College/St_Johns_College_MS_111.xml, collections/St_Johns_College/St_Johns_College_MS_118.xml, collections/St_Johns_College/St_Johns_College_MS_266.xml
New entries - SJC MSS 111, 118, and 266
=> SJC Batch 35

collections/St_Johns_College/St_Johns_College_MS_127.xml, collections/St_Johns_College/St_Johns_College_MS_54.xml, collections/St_Johns_College/St_Johns_College_MS_89.xml
New entries - MSS 54, 89, and 127
=> SJC Batch 36

collections/St_Johns_College/St_Johns_College_MS_123.xml, collections/St_Johns_College/St_Johns_College_MS_143.xml, collections/St_Johns_College/St_Johns_College_MS_177.xml
New entries - MS 123, MS 143, MS 177
=> SJC Batch 37

collections/St_Johns_College/St_Johns_College_MS_320.xml, collections/St_Johns_College/St_Johns_College_MS_96.xml, collections/St_Johns_College/St_Johns_College_MS_99.xml
New entries - MS 96, MS 99, MS 320
=> SJC Batch 38

collections/Hertford_College/Hertford_College_MS_1.xml, collections/Hertford_College/Hertford_College_MS_2.xml, collections/Hertford_College/Hertford_College_MS_3.xml, collections/Hertford_College/Hertford_College_MS_4.xml, collections/Hertford_College/Hertford_College_MS_41.xml, collections/Hertford_College/Hertford_College_MS_5.xml
@andrew-morrison 6 manuscripts from Hertford College. These are on deposit with the Bodleian so orderable via Aeon. I'm aware there are some validation errors (missing keys) which I'll fix once the branch is merged.
=> New collection (Hertford college mss)

collections/St_Johns_College/St_Johns_College_MS_10.xml, collections/St_Johns_College/St_Johns_College_MS_136.xml, collections/St_Johns_College/St_Johns_College_MS_15.xml
=> SJC Batch 39

collections/St_Johns_College/St_Johns_College_MS_124.xml, collections/St_Johns_College/St_Johns_College_MS_132.xml, collections/St_Johns_College/St_Johns_College_MS_152.xml, collections/St_Johns_College/St_Johns_College_MS_158.xml, collections/St_Johns_College/St_Johns_College_MS_185.xml, collections/St_Johns_College/St_Johns_College_MS_344.xml, collections/St_Johns_College/St_Johns_College_MS_36.xml, collections/St_Johns_College/St_Johns_College_MS_56.xml, collections/St_Johns_College/St_Johns_College_MS_86.xml
New entries - MSS 56, 124, and 344
=> SJC Batch 40

collections/St_Johns_College/St_Johns_College_MS_1.xml, collections/St_Johns_College/St_Johns_College_MS_101.xml, collections/St_Johns_College/St_Johns_College_MS_126.xml, collections/St_Johns_College/St_Johns_College_MS_153.xml, collections/St_Johns_College/St_Johns_College_MS_182.xml, collections/St_Johns_College/St_Johns_College_MS_48.xml, collections/St_Johns_College/St_Johns_College_MS_6.xml, collections/St_Johns_College/St_Johns_College_MS_75.xml
New entries - MSS 6, 48, 75, 101, 153, 182
=> SJC Batch 43

collections/St_Johns_College/St_Johns_College_MS_154.xml
=> SJC Batch 45

collections/Douce/MS_Douce_248.xml
@adunning Henrike has had a look at this (mainly to check the transcriptions from Dutch) but do cast your eye over it!
=> MS. Douce 248, new description

collections/Clarendon_Press/MS_Clar_Press_b_2.xml, collections/Clarendon_Press/MS_Clar_Press_b_3.xml, collections/Morrell/MS_Morrell_11.xml, collections/Morrell/MS_Morrell_20.xml, collections/Morrell/MS_Morrell_25.xml, collections/Morrell/MS_Morrell_3.xml, collections/Morrell/MS_Morrell_4.xml, collections/St_Amand/MS_St_Amand_32.xml, collections/St_Amand/MS_St_Amand_39.xml, collections/St_Amand/MS_St_Amand_53.xml, collections/St_Amand/MS_St_Amand_64.xml
For review and merging by @andrew-morrison for Aeon / central storage facility integration
=> offsite manuscripts: update availability and add barcodes

collections/Laud_Misc/MS_Laud_Misc_1831-2.xml, collections/Laud_Misc/MS_Laud_Misc_203.xml, collections/Laud_Misc/MS_Laud_Misc_208.xml, collections/Laud_Misc/MS_Laud_Misc_228.xml, collections/Laud_Misc/MS_Laud_Misc_313.xml
MSS Misc. 183(/1 and /2), 203, 208, 228 and 313
=> MSS Update 11/08/2023

collections/St_Johns_College/St_Johns_College_MS_128.xml, collections/St_Johns_College/St_Johns_College_MS_134.xml, collections/St_Johns_College/St_Johns_College_MS_150.xml, collections/St_Johns_College/St_Johns_College_MS_172.xml, collections/St_Johns_College/St_Johns_College_MS_178.xml, collections/St_Johns_College/St_Johns_College_MS_184.xml, collections/St_Johns_College/St_Johns_College_MS_188.xml, collections/St_Johns_College/St_Johns_College_MS_197.xml, collections/St_Johns_College/St_Johns_College_MS_200.xml, collections/St_Johns_College/St_Johns_College_MS_257.xml, collections/St_Johns_College/St_Johns_College_MS_293.xml, collections/St_Johns_College/St_Johns_College_MS_82.xml
New entries - MSS 134, 150, 188
=> SJC Batch 51

collections/Laud_Misc/MS_Laud_Misc_477.xml, collections/Laud_Misc/MS_Laud_Misc_478.xml, collections/Laud_Misc/MS_Laud_Misc_480.xml, collections/Laud_Misc/MS_Laud_Misc_483.xml, collections/Laud_Misc/MS_Laud_Misc_493.xml
MSS Laud Misc. 477, 478, 480, 493 and work keys.
=> Pull request 06/10/2023

collections/Laud_Misc/MS_Laud_Misc_195.xml, collections/Laud_Misc/MS_Laud_Misc_228.xml, collections/Laud_Misc/MS_Laud_Misc_313.xml, collections/Laud_Misc/MS_Laud_Misc_315.xml, collections/Laud_Misc/MS_Laud_Misc_318.xml, collections/Laud_Misc/MS_Laud_Misc_319.xml, collections/Laud_Misc/MS_Laud_Misc_323.xml, collections/Laud_Misc/MS_Laud_Misc_324.xml, collections/Laud_Misc/MS_Laud_Misc_325.xml, collections/Laud_Misc/MS_Laud_Misc_380.xml, collections/Laud_Misc/MS_Laud_Misc_386.xml, collections/Laud_Misc/MS_Laud_Misc_390.xml, collections/Laud_Misc/MS_Laud_Misc_410.xml, collections/Laud_Misc/MS_Laud_Misc_493.xml
MSS. Laud Misc. 195, 228, 313, 315, 318, 319, 323, 324, 325, 380, 386, 390, 410 & 493.
=> Add facsimile links for Mainz items

collections/Laud_Misc/MS_Laud_Misc_179.xml, collections/Laud_Misc/MS_Laud_Misc_180.xml, collections/Laud_Misc/MS_Laud_Misc_190.xml, collections/Laud_Misc/MS_Laud_Misc_191.xml, collections/Laud_Misc/MS_Laud_Misc_405.xml
MSS Laud Misc 179, 180, 190, 191 and 405 + work key sheet
=> Pull request 17/10/2023

collections/St_Johns_College/St_Johns_College_MS_130.xml, collections/St_Johns_College/St_Johns_College_MS_147.xml, collections/St_Johns_College/St_Johns_College_MS_149.xml, collections/St_Johns_College/St_Johns_College_MS_164.xml, collections/St_Johns_College/St_Johns_College_MS_173.xml, collections/St_Johns_College/St_Johns_College_MS_190.xml, collections/St_Johns_College/St_Johns_College_MS_202.xml, collections/St_Johns_College/St_Johns_College_MS_235_fragment_114.xml, collections/St_Johns_College/St_Johns_College_MS_254.xml, collections/St_Johns_College/St_Johns_College_MS_265.xml, collections/St_Johns_College/St_Johns_College_MS_77.xml, collections/St_Johns_College/St_Johns_College_MS_98.xml
write arks to MSS. 77, 98, 130, 147, 164, 173, 190, 202, 235 fragment 114, 254.
Also added to MS. 149 and MS. 265
=> write arks

collections/Laud_Misc/MS_Laud_Misc_180.xml, collections/Laud_Misc/MS_Laud_Misc_221.xml, collections/Laud_Misc/MS_Laud_Misc_584.xml, collections/Laud_Misc/MS_Laud_Misc_650.xml, collections/Laud_Misc/MS_Laud_Misc_677.xml, collections/Laud_Misc/MS_Laud_Misc_737.xml, collections/Laud_Misc/MS_Laud_Misc_738.xml
MSS Laud Misc. 221, 584, 650, 677, 737 and 738. Also correction made to MS. Laud Misc. 180.
=> Pull Request 17/11/2023

collections/Lat_hist/MS_Lat_hist_a_2.xml, collections/Laud_Misc/MS_Laud_Misc_506.xml, collections/Laud_Misc/MS_Laud_Misc_574.xml, collections/St_Johns_College/St_Johns_College_MS_134.xml, collections/St_Johns_College/St_Johns_College_MS_164.xml, collections/St_Johns_College/St_Johns_College_MS_194.xml
MSS. Laud Misc. 506 & 574; St John's College MSS 134 & 194.
=> Add facsimile links for Mainz and St John's items

collections/Laud_Misc/MS_Laud_Misc_187.xml, collections/Laud_Misc/MS_Laud_Misc_401.xml, collections/Laud_Misc/MS_Laud_Misc_474.xml, collections/Laud_Misc/MS_Laud_Misc_475.xml, collections/Laud_Misc/MS_Laud_Misc_484.xml, collections/Laud_Misc/MS_Laud_Misc_721.xml, collections/Laud_lat/MS_Laud_Lat_28.xml
MS. Laud Lat 28 + MSS Laud Misc. 187, 401, 474, 475, 484, and 721
=> Pull Request 01/05/2024

collections/Laud_Misc/MS_Laud_Misc_352.xml, collections/Laud_Misc/MS_Laud_Misc_378.xml, collections/Laud_Misc/MS_Laud_Misc_584.xml, collections/Laud_Misc/MS_Laud_Misc_650.xml, collections/Laud_Misc/MS_Laud_Misc_677.xml, collections/Laud_Misc/MS_Laud_Misc_737.xml, collections/Laud_Misc/MS_Laud_Misc_738.xml, collections/Laud_lat/MS_Laud_Lat_29-star.xml, collections/Laud_lat/MS_Laud_Lat_29.xml, collections/St_Johns_College/St_Johns_College_MS_154.xml
MSS. Laud Lat. 29 & 29*; MSS. Laud Misc. 352, 378, 584, 650, 677, 737 & 738; St John's College MS. 154.
=> Add facsimile links for Mainz/SJC items

collections/DOrville/MS_DOrville_207.xml, collections/DOrville/MS_DOrville_209.xml
Remove facsimile link from MS. D'Orville 207, add facsimile link to MS. D'Orville 209.
=> Amend facsimile links for MSS. D'Orville 207 & 209

collections/Arch_Selden/MS_Arch_Selden_A_2.xml, collections/Bodl/MS_Bodl_775.xml, collections/Douce/MS_Douce_311_adds_1.xml, collections/Douce/MS_Douce_311_adds_2.xml, collections/Laud_Misc/MS_Laud_Misc_1831-2.xml, collections/Laud_Misc/MS_Laud_Misc_187.xml, collections/Laud_Misc/MS_Laud_Misc_221.xml, collections/Laud_Misc/MS_Laud_Misc_401.xml, collections/Laud_Misc/MS_Laud_Misc_474.xml, collections/Laud_Misc/MS_Laud_Misc_475.xml, collections/Laud_Misc/MS_Laud_Misc_484.xml, collections/Laud_Misc/MS_Laud_Misc_721.xml, collections/Laud_lat/MS_Laud_Lat_28.xml, collections/St_Johns_College/St_Johns_College_MS_57.xml, collections/St_Johns_College/St_Johns_College_MS_86.xml
Mainz: MS. Laud Lat. 28; MSS. Laud Misc. 183/1-2, 187, 221, 401, 474, 475, 484 & 721.
Others: MS. Bodl. 775; MS. Douce 311 adds. 1 & 2; MS. Arch. Selden. A.2; St John's College MSS. 57 & 86.
=> Add facsimile links for Mainz and other items

collections/St_Johns_College/St_Johns_College_MS_143.xml, collections/St_Johns_College/St_Johns_College_MS_56.xml
=> Add facsimile links for St John's College items

collections/Brasenose/Brasenose_College_MS_91.xml, collections/St_Johns_College/St_Johns_College_MS_94.xml
Brasenose College MS 91 & St John's College MS 94.
=> Add facsimile links for college items

collections/Canon_Misc/MS_Canon_Misc_172.xml, collections/DOrville/MS_DOrville_148.xml, collections/Douce/MS_Douce_79.xml, collections/St_Johns_College/St_Johns_College_MS_257.xml
St John's College MS 257; MS. Douce 79; MS. D'Orville 148; MS. Canon. Misc. 172.
=> Add facsimile links

collections/Bodl/MS_Bodl_204.xml, collections/Bodl/MS_Bodl_578.xml, collections/Hatton/MS_Hatton_57.xml, collections/Rawl_G/MS_Rawl_G_112.xml
add arks back in that were lost in retro-con.
=> re-add_arks

collections/Canon_Gr/MS_Canon_Gr_122.xml, collections/Douce/MS_Douce_176.xml
MS. Canon. Gr. 122, MS. Douce 176.
=> Add facsimile links for digitized items

collections/Jesus_College/Jesus_College_MS_3.xml, collections/St_Johns_College/St_Johns_College_MS_128.xml, collections/St_Johns_College/St_Johns_College_MS_167.xml, collections/St_Johns_College/St_Johns_College_MS_6.xml
Jesus College MS. 3; St John's College MSS 6, 128, 167.
=> Add facsimile links to college items

collections/Bodl/MS_Bodl_309.xml, collections/St_Johns_College/St_Johns_College_MS_208.xml, collections/St_Johns_College/St_Johns_College_MS_58.xml
MS. Bodl. 309; St John's College MSS 58, 208.
=> Add facsimile links for DB items

collections/Arch_Selden/MS_Arch_Selden_A_72_3.xml, collections/Auct_F/MS_Auct_F_6_1.xml, collections/Duke_Humfrey/MS_Duke_Humfrey_c_1.xml, collections/Gr_class/MS_Gr_class_a_6_P.xml, collections/Gr_class/MS_Gr_class_c_27_P.xml, collections/Gr_class/MS_Gr_class_c_59_P.xml, collections/Hatton/MS_Hatton_48.xml, collections/Selden_supra/MS_Selden_Supra_30.xml
- MS. Arch. Selden. A. 72 (3)
- MS. Auct. F. 6. 1
- MS. Duke Humfrey c. 1
- MS. Gr. class. a. 6 (P)
- MS. Gr. class. c. 27 (P)
- MS. Gr. class. c. 59 (P)
- MS. Hatton 48
- MS. Selden Supra 30
=> Facsimile links 2025 04 09

collections/Broxb/MS_Broxb_857.xml, collections/Douce/MS_Douce_311.xml, collections/Gr_class/MS_Gr_class_f_48_P.xml, collections/Gr_liturg/MS_Gr_liturg_c_1.xml, collections/St_Johns_College/St_Johns_College_MS_18.xml, collections/St_Johns_College/St_Johns_College_MS_204.xml, collections/St_Johns_College/St_Johns_College_MS_254.xml, collections/St_Johns_College/St_Johns_College_MS_28.xml, collections/St_Johns_College/St_Johns_College_MS_293.xml, collections/St_Johns_College/St_Johns_College_MS_76.xml
- St John's College MSS 18, 28, 76, 204, 254, 293
- MS. Douce 311
- MS. Gr. class. f. 48 (P) [link to removed digital object replaced with link to new version]
- MS. Gr. liturg. c. 1
- MS. Broxb. 85.7
=> Add facsimile links to digitzed items

collections/Canon_Liturg/MS_Canon_Liturg_169.xml, collections/Canon_Liturg/MS_Canon_Liturg_170.xml, collections/Canon_Liturg/MS_Canon_Liturg_240.xml, collections/Canon_Liturg/MS_Canon_Liturg_30.xml, collections/Canon_Liturg/MS_Canon_Liturg_31.xml
=> Retro-conversion
